### ISSUE TITLE
Why is the attribution in the website misleading?

### ISSUE THREAD

**Issue by ezzarghili** [Wiqaytna-app/wiqaytna_android#10]
Attribution in the website states

![image](https://user-images.githubusercontent.com/8616968/83449587-c8684300-a44b-11ea-85ef-910139d2b565.png)

Where the original code for the application was developed by https://github.com/opentrace-community/opentrace-android

**Comment by abderrahmane-tj** [comment]
You're being too nice. It 100% says, it's made only by moroccan authorities...

**Comment by ezzarghili** [comment]
Question clarified by Zouheir LAKHDISSI in https://www.facebook.com/geeksblabla/videos/184114139689813/UzpfSTEyMjcwNDQ1MTY6MTA2NjY2NzM4MDQwMTkwNQ/
Ref https://github.com/Wiqaytna-app/wiqaytna_android/blob/master/ATTRIBUTION.md
I still have some conservations about the website and hope it will be updated, but his should be enough for the actual source of the app (in this case this repo)
