### ISSUE TITLE
No matching client found for package name 'covid.trace.morocco.stg'

### ISSUE THREAD

**Issue by AchrafLaabassi** [Wiqaytna-app/wiqaytna_android#14]
Hello ! 

I understand that the project is to be linked to a Firebase database , I did create the project in Firebase with the application name in the build.gradle and downloaded the google-services.json but i have this recurrent problem " No matching client found for package name 'covid.trace.morocco.stg' ", Has anyone worked around this ? Am I following steps wrong ? 

Thank you !

**Comment by n-eq** [comment]
You can make the following change
```diff
-            applicationIdSuffix "stg"
+            applicationIdSuffix ""
```

in app/build.gradle

**Comment by AchrafLaabassi** [comment]
Thanks it worked
