### ISSUE TITLE
Could not get unknown property 'ERROR_NOTIFICATION_ID' for DefaultConfig

### ISSUE THREAD

**Issue by AchrafLaabassi** [Wiqaytna-app/wiqaytna_android#15]
Hello,

I have this message error when trying to run the app.

Could not get unknown property 'ERROR_NOTIFICATION_ID' for DefaultConfig_Decorated{name=main, dimension=null, minSdkVersion=DefaultApiVersion{mApiLevel=22, mCodename='null'}, targetSdkVersion=DefaultApiVersion{mApiLevel=28, mCodename='null'}, renderscriptTargetApi=null, renderscriptSupportModeEnabled=null, renderscriptSupportModeBlasEnabled=null, renderscriptNdkModeEnabled=null, versionCode=66, versionName=1.0.66, applicationId=covid.trace.morocco, testApplicationId=null, testInstrumentationRunner=androidx.test.runner.AndroidJUnitRunner, testInstrumentationRunnerArguments={}, testHandleProfiling=null, testFunctionalTest=null, signingConfig=null, resConfig=null, mBuildConfigFields={ADVERTISING_DURATION=com.android.builder.internal.ClassFieldImpl@e4896733, ADVERTISING_INTERVAL=com.android.builder.internal.ClassFieldImpl@26ba6496, BLACKLIST_DURATION=com.android.builder.internal.ClassFieldImpl@4b062da4, BM_CHECK_INTERVAL=com.android.builder.internal.ClassFieldImpl@50f6ddca, CONNECTION_TIMEOUT=com.android.builder.internal.ClassFieldImpl@94c7c7f5, FIREBASE_REGION=com.android.builder.internal.ClassFieldImpl@3372c2e2, GITHASH=com.android.builder.internal.ClassFieldImpl@863c1b71, HEALTH_CHECK_INTERVAL=com.android.builder.internal.ClassFieldImpl@271b9013, MAX_QUEUE_TIME=com.android.builder.internal.ClassFieldImpl@c74bda7e, MAX_SCAN_INTERVAL=com.android.builder.internal.ClassFieldImpl@9c610c20, MIN_SCAN_INTERVAL=com.android.builder.internal.ClassFieldImpl@2c39938e, ORG=com.android.builder.internal.ClassFieldImpl@33c10f52, PRIVACY_URL=com.android.builder.internal.ClassFieldImpl@817c296f, PURGE_INTERVAL=com.android.builder.internal.ClassFieldImpl@537346fc, PURGE_TTL=com.android.builder.internal.ClassFieldImpl@359f3409, PUSH_NOTIFICATION_CHANNEL_NAME=com.android.builder.internal.ClassFieldImpl@f232aec2, PUSH_NOTIFICATION_ID=com.android.builder.internal.ClassFieldImpl@294f40a9, SCAN_DURATION=com.android.builder.internal.ClassFieldImpl@d2e6853d, SERVICE_FOREGROUND_CHANNEL_ID=com.android.builder.internal.ClassFieldImpl@69207f4d, SERVICE_FOREGROUND_CHANNEL_NAME=com.android.builder.internal.ClassFieldImpl@56682d53, SERVICE_FOREGROUND_NOTIFICATION_ID=com.android.builder.internal.ClassFieldImpl@73e73b77, STORE_URL=com.android.builder.internal.ClassFieldImpl@ba118421, V2_CHARACTERISTIC_ID=com.android.builder.internal.ClassFieldImpl@3d1d5243}, mResValues={build_config_package=com.android.builder.internal.ClassFieldImpl@691e6d4}, mProguardFiles=[], mConsumerProguardFiles=[], mManifestPlaceholders={}, mWearAppUnbundled=null} of type com.android.build.gradle.internal.dsl.DefaultConfig.

I understand the program cannot find a value for ERROR_NOTIFICATION_ID, when i do delete the line the programs tells me that it is needed in the code.

Any Idea what to do here ?
Thank you !

**Comment by hichamboushaba** [comment]
@AchrafLaabassi you need to add `ERROR_NOTIFICATION_ID` to your gradle.properties file, it's missing from the README: https://github.com/Wiqaytna-app/wiqaytna_android/pull/2
