### ISSUE TITLE
This list in the picture should be ordered by percentage

### ISSUE THREAD

**Issue by chadidi** [Wiqaytna-app/wiqaytna_android#18]
This list should be ordered by percentage from the biggest percentage to the smallest, 

![WhatsApp Image 2020-06-02 at 3 33 03 PM](https://user-images.githubusercontent.com/9916806/83533022-f5b5ff00-a4e6-11ea-88ff-f9b1c9efa13b.jpeg)

**Comment by ans1genie** [comment]
It would be useful to put the number!
