### ISSUE TITLE
Inclusion in F-droid

### ISSUE THREAD

**Issue by Dragnucs** [Wiqaytna-app/wiqaytna_android#26]
Please consider submitting the application to F-droid.

Submission link: https://gitlab.com/fdroid/rfp/-/issues/1372

What is mostly required is a [fastlane](https://gitlab.com/snippets/1895688) file structure and tagging releases. I might help with that.

Additionally, to enhance privacy respect, please provide a so called *untainted* build with no dependencies to crashlytics and firebase or other proprietary dependencies.

Keep up the good work! I am glad Morocco is releasing a foundational, quality, privacy reviewed, and FLOSS application.

**Comment by licaon-kter** [comment]
> Additionally, to enhance privacy respect

It's not about that, the main F-Droid repo hosts only full free open-source apps. If it links to Google Services/Firebase/Crashlytics/etc libs, which are closed sourced, it can't be included.

**Comment by Dragnucs** [comment]
F-droid hosts application that are at the same time FLOSS and privacy friendly. The application at hand lacks in the later.

[Inclusion Policy](https://f-droid.org/docs/Inclusion_Policy/?title=Inclusion_Policy)

Instead of debating what it is about or not, lets contribute to make this even better, and privacy respecting.

**Comment by Abdelwahad** [comment]
Thank you very much for this interesting proposal, but as @licaon-kter pointed out, the use of Firebase is not allowed by F-droid.

**Comment by Dragnucs** [comment]
Why is firebase used in this application anyway? Can't an alternative be used? Like knative or other databases.

**Comment by smege1001** [comment]
@licaon-kter
> If it links to Google Services/Firebase/Crashlytics/etc libs, which are closed sourced, it can't be included.

It might get included, but with an anti-feature warning that says that [the upstream source code is not free and some parts of source code may get rewritten or replaced to remove the non-free libraries or code](https://f-droid.org/wiki/page/Antifeature:UpstreamNonFree)

**Comment by licaon-kter** [comment]
@smege1001 nope, and if that was the case for older apps in the past it is no more. 

The Wiki is obsolete since Dec 2018, there only 4 pages there, related to current build output, that are still updated.

**Comment by Dragnucs** [comment]
@Abdelwahad can you reconsider this issue?
This will also solve other issues like #38.

**Comment by Abdelwahad** [comment]
@Dragnucs Sorry, we will not move from firebase in a near futur. Anyway, thanks a lot for your proposal.

**Comment by Dragnucs** [comment]
I understand not wanting to move away from firebase, but can you please explain this choice? Using a proprietary library while you want to have a fully free and open source stack.

**Comment by licaon-kter** [comment]
@Abdelwahad is this about a database software or about having a dependency on Google Services?

**Comment by Dragnucs** [comment]
Both. The stack starts from the what runs on the mobile, transport layers than what is used in the back-end server.
For example, even if this application is open source, it forces us to use proprietary privacy intrusive dependencies. Google services for instance.

**Comment by licaon-kter** [comment]
@Dragnucs I wasn't asking you, I wasn't asking that

**Comment by smege1001** [comment]
Using proprietary libraries absolutely ruins the point of being about privacy.
