### ISSUE TITLE
L'application ne se lance pas après le redémarrage du téléphone 

### ISSUE THREAD

**Issue by yassinedrissi87** [Wiqaytna-app/wiqaytna_android#30]
Quand je redémarre le téléphone, l'application ne se lance pas après le redémarrage du téléphone. 
Par contre quand je désactive la gestion automatique du lancement de l'application dans les détails de consommation de l'énergie de l'application , pour passer à "gérée manuellement", l'application se lance après le redémarrage du téléphone , à condition qu'elle soit déjà en cours d'exécution avant le redémarrage du téléphone.
![Screenshot_20200606_014516_com huawei systemmanager](https://user-images.githubusercontent.com/12575367/83936688-e4f2db00-a7bd-11ea-8497-f88bd32bd699.jpg)

**Comment by yassinedrissi87** [comment]
J'ai ouvert l'application, et j'ai procédé à quelques redémarrages du téléphone avec une gestion manuelle des lancements, puis à d'autres redémarrages avec une gestion automatique des lancements. 
Ci-dessous les resultats
- Le lancement est gèrée manuellement : le nombre des lancements autorisés s'incrémente à chaque redémarrage.
![Screenshot_20200606_185047_com huawei systemmanager](https://user-images.githubusercontent.com/12575367/83952119-6f732300-a82e-11ea-869e-e891d15c0d32.jpg)

- Le lancement est gèrée automatiquement : le nombre des lancements interdits s'incrémente à chaque redémarrage.
![Screenshot_20200606_185025_com huawei systemmanager](https://user-images.githubusercontent.com/12575367/83952122-7863f480-a82e-11ea-887f-318c0e741096.jpg)

**Comment by Abdelwahad** [comment]
Issue ayant la même origine que  #29
