### ISSUE TITLE
Les notifications discrètes 

### ISSUE THREAD

**Issue by yassinedrissi87** [Wiqaytna-app/wiqaytna_android#33]
L'appliction n'a qu'un seul type de notification :  les notifications discrètes. 
Je pense qu'il faut définir un deuxième type de notifications qui attire l'attention, si l'application devrait envoyer des notifications importantes à un certain moment à l'utilisateur.

**Comment by Abdelwahad** [comment]
Merci pour le conseil, nous enverrons des notifs si besoin
