### ISSUE TITLE
The application can be downloaded outside of Morocco

### ISSUE THREAD

**Issue by DouiriAli** [Wiqaytna-app/wiqaytna_android#4]
The application can be downloaded in France. Normally it must be available in Morocco only.

**Comment by Marouane-AQUIL** [comment]
Up @DouiriAli

**Comment by AchrafAmil** [comment]
Why not ?

**Comment by Marouane-AQUIL** [comment]
to not test on the French.

**Comment by ans1genie** [comment]
Apparently, it looks similar to the [OpenTrace Community ](https://github.com/opentrace-community/)of Singapore!

Is it the same and works in the same way, how the data will be handled?

If it is the same but only official clients for each country to adapt UI:
It can be good for Moroccans traveling or are now outside and don't know foreign languages or preferring AR!

Else, a good a useful use-case, is when someone enters Morocco he can pre-installed it on his phone before?
But It should provide a way to activate and deactivate the app!

**Comment by iothmane** [comment]
I'm not sure we should limit the stores where the app can be downloaded as people with devices set to non moroccan stores and currently living in morocco can download it.

**Comment by ezzarghili** [comment]
I think keeping Downloadable from anywhere is not an issue, people visiting later on can download the app before entering Moroccan territory, this will help tracking in airports and transport means...

**Comment by aeramli** [comment]
Yeah, but I hope it will not false the data/analytics behind (I mean if people start using it outside of Morocco)

**Comment by iothmane** [comment]
Since everything is private and on device nothing is shared until you enter the specific code given by the health ministry! Something you won’t be able to do outside of Morocco 😀

**Comment by IhabBendidi** [comment]
Another possible issue is servers doing the tracing/matching might have a big overload if hypothetically too many foreign people install the application.

**Comment by ezzarghili** [comment]
@IhabBendidi matching should happen only for people who already were confirmed positive by the government.
So no overload on servers.

**Comment by AchrafAmil** [comment]
Restricting Google Play deployment geographically won't be that efficient if the app is open source and can be cloned/built publicly.
Overload risk is quite low, the app should anyway be resilient for scaled usage. At worst, temporarily restricting foreign IP addresses might help surviving an overload if any.

**Comment by taharh** [comment]
> Since everything is private and on device nothing is shared until you enter the specific code given by the health ministry! Something you won’t be able to do outside of Morocco grinning

if you have a Moroccan SIM card outside of morocco you can still receive the code in SMS

**Comment by ans1genie** [comment]
@taharh 
So it can't be used outside MA, for tourist for example?

**Comment by malekairmaroc7** [comment]
@ans1genie 
If the tourist still have the SIM Card he/she bought then the tourist can use the app even outside of Morocco. (I still have Inwi for example and I got the SMS even outside of Morocco)

**Comment by malekairmaroc7** [comment]
Also, for me its amazing what Morocco did for an application that almost the whole world is developing too and of course I don't say no to test it outside Morocco 😁.
(If its not on the Play Store, you surely may find the latest release on trusted sites like APKMirror)

**Comment by Abdelwahad** [comment]
> I think keeping Downloadable from anywhere is not an issue, people visiting later on can download the app before entering Moroccan territory, this will help tracking in airports and transport means...

Indeed, this does not hurt, and can be useful for some of the users who would like it to be active as soon as they arrive in Morocco, especially if they have a valid Moroccan SIM abroad
