### ISSUE TITLE
The released playstore version is 1.0.67 while the repository one is 1.0.66

### ISSUE THREAD

**Issue by medyo** [Wiqaytna-app/wiqaytna_android#5]
Please update the current repository with the same code version as published on production (playstore)

<img src="https://user-images.githubusercontent.com/2389584/83425128-5250e580-a425-11ea-9aea-45c9fa02575b.png" alt="drawing" width="300"/>

Thanks

**Comment by zlakhdissi** [comment]
Two minor releases were developed since yesterday to makr some corrections (1.0.67 and 1.0.68) they will be pushed tonight inchaallah

**Comment by ezzarghili** [comment]
I guess you would want to push code before publishing, so people get the chance to review code before installing.

**Comment by aeramli** [comment]
That means no CI/CD, and no Test :'(

**Comment by seuros** [comment]
@aeramli  Covid tests are expensive. 7819 failing test to day.

**Comment by medyo** [comment]
### Update: two new other versions have been pushed (1.0.68 and 1.0.69)
It seems that this repository is useless since it's not synced with the production one.
Are we pouring water in the sand? 🤔
_____
<img src="https://user-images.githubusercontent.com/2389584/83530139-3c095f00-a4e3-11ea-9dfd-ee0c6dfb328a.png" alt="drawing" width="200"/>
