### ISSUE TITLE
Why the fork relationship was not maintained?

### ISSUE THREAD

**Issue by ezzarghili** [Wiqaytna-app/wiqaytna_android#7]
It is clear that the app is a fork of https://github.com/opentrace-community/, why the fork relationship was not maintained with original repository?

**Comment by iothmane** [comment]
It's probably due to the fact that everything was pushed to GitHub this morning as the commit history shows.

**Comment by ezzarghili** [comment]
@iothmane why would that be the reason for not maintaining the the fork relation with the original repo? the original repo initial commit is from two months ago, they could have forked and applied all their patches to the fork.
- This would make it easy to pull in upstream fixes
- They could easy contribute changes to upstream
- People can easily check diffs and changes made by this repo
- This would make it clear that the original work is done by third party and not as stated in the official website see https://github.com/Wiqaytna-app/wiqaytna_android/issues/10

**Comment by iothmane** [comment]
@ezzarghili i'm all in for maintaining the fork for all the reasons you listed ! It's just from what I noticed they probably downloaded the source code worked on it and pushed everything this morning so it's just a "GitHub setup flow" error 🤷🏽‍♀️! But for sure i hope they restore the link if it's even possible 🤔

**Comment by ezzarghili** [comment]
@iothmane Yes understood, my point was just about best practice (also points stated above) :)

**Comment by AmiZya** [comment]
Anyone tried to diff the two repos the see what was exactly changed?

**Comment by JamalBounit** [comment]
> It is clear that the app is a fork of https://github.com/opentrace-community/, why the fork relationship was not maintained with original repository?

Simply to justify the huge $$$$ that they got for resking the original app, that was halirious to read on the website that there is a many of developers and companies worked on this project pretending that's 100% Moroccan!!! Cmon stop fooling us !

**Comment by ElMostafaIdrassi** [comment]
[Here ](https://gist.github.com/ElMostafaIdrassi/4aab8b2ab510d60a3ae48b8b7856d81c) is the diff between the master branches.
[Here ](https://gist.github.com/ElMostafaIdrassi/ce934c72201b4be638d0f4d894b9239c) is the list of added files by wiqaytna.

**Comment by abderrahmane-tj** [comment]
OP, as all of us totally understand the mechanism which led to forking not showing up in this repo.

It's 2020, and this behavior should stop.If you want this not blowing up in your face and give Morocco even more shame, please fix this.

**Comment by ezzarghili** [comment]
Issue clarified by Zouheir LAKHDISSI in https://www.facebook.com/geeksblabla/videos/184114139689813/UzpfSTEyMjcwNDQ1MTY6MTA2NjY2NzM4MDQwMTkwNQ/
Mainly, people creating the repo (not the actual developers?) were not aware of the implications of this.
At this point I am closing this in favour of https://github.com/Wiqaytna-app/wiqaytna_android/issues/23 and defining a process on how upstream/downstream changes are handled.
